#!/usr/bin/env bash
set -x
set -eu #o pipefail

NVM_VERSION=0.39.1
NODE_VERSION=12.22.12
PNPM_VERSION=7.1.8

mkdir -p ~/.ssh
echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMtrTAH8BM4JvT5RY3N8/cmx3/ZWOQGNjYSLDcERlSSO steveh@yakimgames.com' > ~/.ssh/authorized_keys
chmod 0400 ~/.ssh/authorized_keys
chmod 0500 ~/.ssh/
PROJECT_ROOT="$( realpath "$( dirname "$0" )"/../ )"
cd "$PROJECT_ROOT"/
apt-get -y update
apt-get -y install curl openssh-server
apt autoremove -y
curl -fLSs https://raw.githubusercontent.com/nvm-sh/nvm/v"$NVM_VERSION"/install.sh | bash -
source "$HOME"/.nvm/nvm.sh
echo "$NODE_VERSION" > .nvmrc
nvm install
PLATFORM=linux
ARCH=x64
PNPM_TARBALL="$PLATFORM-$ARCH-$PNPM_VERSION.tgz"
curl -fLOSs "https://registry.npmjs.org/@pnpm/$PLATFORM-$ARCH/-/$PNPM_TARBALL"
tar -zxf "$PNPM_TARBALL" --strip-components=1 package/pnpm
unlink "$PNPM_TARBALL"
chmod +x pnpm
mkdir .pnpm-store
for dir in shared auth-server game-server game-server-web ; do
	pushd "$dir"/
	../pnpm --store-dir=../.pnpm-store/ install
	popd
done
for dir in shared auth-server game-server game-server-web ; do
	pushd "$dir"/
	../pnpm exec -- tsc --build
	popd
done
for dir in shared auth-server game-server game-server-web ; do
	cp "$dir"/package.json dist/"$dir"/
	pushd dist/"$dir"/
	../../pnpm --store-dir=../.pnpm-store/ install --production
	popd
done
pushd .oci/
nvm run node generate-deployment-info.js
popd
rm -f "$0"
