#!/usr/bin/env bash
#set -x
set -euo pipefail

NVM_VERSION=0.39.1
NODE_VERSION=12.22.12
PNPM_VERSION=7.1.8

PROJECT_ROOT="$( realpath "$( dirname "$0" )"/../ )"
cd "$PROJECT_ROOT"/
apt-get -y update
apt-get -y install curl
apt autoremove -y
curl -fLSs https://raw.githubusercontent.com/nvm-sh/nvm/v"$NVM_VERSION"/install.sh | bash -
source "$HOME"/.nvm/nvm.sh
echo "$NODE_VERSION" > .nvmrc
nvm install
PLATFORM=linux
ARCH=x64
PNPM_TARBALL="$PLATFORM-$ARCH-$PNPM_VERSION.tgz"
curl -fLOSs "https://registry.npmjs.org/@pnpm/$PLATFORM-$ARCH/-/$PNPM_TARBALL"
tar -zxf "$PNPM_TARBALL" --strip-components=1 package/pnpm
unlink "$PNPM_TARBALL"
chmod +x pnpm
mkdir .pnpm-store
for dir in shared auth-server game-server game-server-web ; do
	pushd "$dir"/
	../pnpm --store-dir=../.pnpm-store/ install
	popd
done
for dir in shared auth-server game-server game-server-web ; do
	pushd "$dir"/
	../pnpm --store-dir=../.pnpm-store/ exec tsc --build
	popd
done
for dir in shared auth-server game-server game-server-web ; do
	if ! [ -f dist/"$dir"/package.json ] ; then
		cp "$dir"/package.json dist/"$dir"/
	fi
	pushd dist/"$dir"/
	../pnpm --store-dir=../.pnpm-store/ install --production
	popd
done
{ env | grep -E '^[^_][a-z0-9_]*=' | sort ; date -u +timestamp_end=%s.%N ; } > .container/deployment.ini
rm -f "$0"
